# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/BCG-DataScience-The-Forage',
                'doc_host': 'https://Ramon-PR.github.io',
                'git_url': 'https://github.com/Ramon-PR/BCG-DataScience-The-Forage',
                'lib_path': 'BCG_DataScience_The_Forage'},
  'syms': { 'BCG_DataScience_The_Forage.core': { 'BCG_DataScience_The_Forage.core.foo': ( 'core.html#foo',
                                                                                          'BCG_DataScience_The_Forage/core.py')}}}
